name: bump
run-name: Bump package version

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["publish"]
    types:
      - completed

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Get tag version
        id: get_version
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Update package.json
        run: npm version ${{ env.VERSION }} --no-git-tag-version --allow-same-version

      - name: Commit updated package.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "bump: Upgrade version to ${{ env.VERSION }}"
          git push origin HEAD
